import os
import sys
import json
import threading
from typing import Annotated
from pydantic import Field

sys.path.insert(
    0, os.path.join(os.path.dirname(__file__), "..")
)

from a2a_messages import create_message, Intent


_synthesis_store: dict = {}
_synthesis_lock = threading.Lock()

# Stores the LLM's reasoning notes from the most recent synthesis attempt.
# On rejection, these are injected back into the retry so the LLM builds
# on its previous thinking rather than starting from scratch.
_reasoning_store: dict = {}


def get_synthesis_result(session_id: str) -> dict | None:
    """Read stored synthesis for a session."""
    return _synthesis_store.get(session_id)



def _extract_node_facts(node_id: str, analysis_id: str, result: dict) -> dict:
    """
    Extract the most important, citable facts from a single analysis result.
    Returns a compact, grounded summary the Synthesis agent can safely cite.
    """
    atype = result.get("analysis_type", "unknown")
    status = result.get("status", "unknown")
    top_finding = result.get("top_finding", "")
    severity = result.get("severity", "info")
    confidence = result.get("confidence", 0.0)
    data = result.get("data", {})

    # Extract the per-node decision-maker insight generated by #10
    _insight_summary = result.get("insight_summary") or {}
    _dm_takeaway = _insight_summary.get("decision_maker_takeaway", "") if isinstance(_insight_summary, dict) else ""

    facts = {
        "node_id": node_id,
        "analysis_id": analysis_id,
        "analysis_type": atype,
        "status": status,
        "top_finding": top_finding,
        "severity": severity,
        "confidence": confidence,
        # Pre-digested decision-maker insight — synthesis should lead with this
        "decision_maker_takeaway": _dm_takeaway,
        "key_metrics": {},
    }

    if status not in ("success",):
        facts["key_metrics"] = {}
        return facts

    # Extract type-specific key metrics for grounding
    # KEY NAMES ARE VERIFIED AGAINST ACTUAL library function return dicts
    if atype in ("distribution_analysis", "distribution"):
        facts["key_metrics"] = {
            "mean": data.get("mean"),
            "median": data.get("median"),
            "std": data.get("std"),
            "outlier_pct": data.get("outlier_pct"),
            "is_normal": data.get("is_normal"),
        }
    elif atype in ("categorical_analysis", "categorical"):
        facts["key_metrics"] = {
            "unique_count": data.get("unique_count"),
            "pareto_ratio": data.get("pareto_ratio"),
            "entropy_ratio": data.get("entropy_ratio"),
            "top_values": data.get("top_10", {}),
        }
    elif atype in ("funnel_analysis",):
        # Actual keys: funnel_metrics, overall_conversion, biggest_drop_step, biggest_drop_pct
        funnel_metrics = data.get("funnel_metrics", [])
        biggest_drop_step = data.get("biggest_drop_step")
        biggest_drop_pct = data.get("biggest_drop_pct")
        facts["key_metrics"] = {
            "total_steps": len(funnel_metrics),
            "overall_conversion": data.get("overall_conversion"),
            "biggest_drop_step": biggest_drop_step,
            "biggest_drop_pct": biggest_drop_pct,
            "funnel_metrics": funnel_metrics[:8],
        }
    elif atype in ("session_detection",):
        # Actual keys: avg_events_per_session, avg_duration_minutes, bounce_rate, bounce_sessions
        facts["key_metrics"] = {
            "total_sessions": data.get("total_sessions"),
            "avg_events_per_session": data.get("avg_events_per_session"),
            "avg_duration_minutes": data.get("avg_duration_minutes"),
            "bounce_rate": data.get("bounce_rate"),
            "bounce_sessions": data.get("bounce_sessions"),
            "detection_mode": data.get("detection_mode"),
        }
    elif atype in ("friction_detection",):
        # Actual keys: top_friction_events, critical_events, high_events, events_analyzed
        top_friction = data.get("top_friction_events", [])
        facts["key_metrics"] = {
            "events_analyzed": data.get("events_analyzed"),
            "critical_events": data.get("critical_events"),
            "high_events": data.get("high_events"),
            "top_friction_events": top_friction[:3],
        }
    elif atype in ("survival_analysis",):
        # Actual keys: median_length, pct_reach_step_10, pct_reach_step_20, critical_dropoff
        critical = data.get("critical_dropoff") or {}
        facts["key_metrics"] = {
            "total_sessions": data.get("total_sessions"),
            "median_session_length": data.get("median_length"),
            "pct_reach_step_10": data.get("pct_reach_step_10"),
            "pct_reach_step_20": data.get("pct_reach_step_20"),
            "critical_dropoff_step": critical.get("step"),
            "critical_dropoff_rate": critical.get("dropout_rate"),
        }
    elif atype in ("user_segmentation",):
        # Actual keys: segments (list), segment_count, total_entities
        segments = data.get("segments", [])
        noise_segments = [s for s in segments if s.get("is_noise")]
        noise_pct = noise_segments[0].get("pct") if noise_segments else 0
        facts["key_metrics"] = {
            "segment_count": data.get("segment_count"),
            "total_entities": data.get("total_entities"),
            "segments": [{"segment_id": s.get("segment_id"), "size": s.get("size"), "pct": s.get("pct"), "characteristics": s.get("characteristics", [])} for s in segments[:5]],
            "noise_pct": noise_pct,
        }
    elif atype in ("dropout_analysis",):
        # Actual keys: early_dropout_pct, top_last_events, median_session_length
        facts["key_metrics"] = {
            "total_sessions": data.get("total_sessions"),
            "early_dropout_pct": data.get("early_dropout_pct"),
            "median_session_length": data.get("median_session_length"),
            "top_last_events": data.get("top_last_events", [])[:3],
            "top_last_2_sequences": data.get("top_last_2_sequences", [])[:3],
        }
    elif atype in ("trend_analysis",):
        facts["key_metrics"] = {
            "trend_direction": data.get("trend_direction"),
            "pct_change": data.get("pct_change"),
            "changepoint_count": len(data.get("changepoints", [])),
            "mann_kendall_significant": (data.get("mann_kendall") or {}).get("significant"),
        }
    elif atype in ("cohort_analysis",):
        facts["key_metrics"] = {
            "cohort_count": data.get("cohort_count"),
            "avg_retention_m1": data.get("avg_retention_month1"),
        }
    elif atype in ("rfm_analysis",):
        facts["key_metrics"] = {
            "total_customers": data.get("total_customers"),
            "champions_pct": data.get("champions_pct"),
            "at_risk_pct": data.get("at_risk_pct"),
        }
    elif atype in ("anomaly_detection",):
        facts["key_metrics"] = {
            "outlier_pct": data.get("outlier_pct"),
            "consensus_outliers": data.get("consensus_outliers"),
            "col": data.get("col"),
        }
    elif atype in ("correlation_matrix", "correlation"):
        notable = data.get("notable_correlations", [])
        facts["key_metrics"] = {
            "notable_correlation_count": len(notable),
            "strongest_pair": notable[0] if notable else None,
        }
    elif atype in ("missing_data_analysis", "missing_data"):
        facts["key_metrics"] = {
            "overall_pct": data.get("overall_pct"),
            "columns_affected": len(data.get("columns_with_missing", [])),
            "complete_rows_pct": data.get("complete_rows_pct"),
        }
    elif atype in ("pareto_analysis",):
        facts["key_metrics"] = {
            "top_20_pct_coverage": data.get("top_20_pct_coverage"),
            "top_items": data.get("top_items", [])[:3],
        }
    elif atype in ("sequential_pattern_mining",):
        facts["key_metrics"] = {
            "pattern_count": data.get("pattern_count"),
            "top_sequences": data.get("top_sequences", [])[:3],
        }
    elif atype in ("transition_analysis",):
        facts["key_metrics"] = {
            "dead_end_events": data.get("dead_end_events", [])[:3],
            "top_loops": data.get("top_loops", [])[:3],
            "highest_exit_event": data.get("highest_exit_event"),
        }
    elif atype in ("event_taxonomy",):
        # Actual keys: category_distribution (dict with count/pct), total_unique_events
        cat_dist = data.get("category_distribution", {})
        dominant = max(cat_dist, key=lambda k: cat_dist[k].get("count", 0)) if cat_dist else None
        facts["key_metrics"] = {
            "total_unique_events": data.get("total_unique_events"),
            "category_distribution": cat_dist,
            "dominant_category": dominant,
        }
    elif atype in ("user_journey_analysis",):
        # Actual keys: avg_steps_per_entity, common_entry_events, common_exit_events
        facts["key_metrics"] = {
            "total_entities_tracked": data.get("total_entities_tracked"),
            "avg_steps_per_entity":   data.get("avg_steps_per_entity"),
            "max_steps_per_entity":   data.get("max_steps_per_entity"),
            "common_entry_events":    data.get("common_entry_events", {}),
            "common_exit_events":     data.get("common_exit_events", {}),
        }
    elif atype in ("intervention_triggers",):
        rules = data.get("rules", [])
        facts["key_metrics"] = {
            "total_sessions": data.get("total_sessions"),
            "rules_found": data.get("rules_found"),
            "high_risk_rules": data.get("high_risk_rules"),
            "medium_risk_rules": data.get("medium_risk_rules"),
            "min_dropout_rate": data.get("min_dropout_rate"),
            "top_rules": rules[:5],
            "narrative": data.get("narrative", {}),
        }
    elif atype in ("session_classification",):
        facts["key_metrics"] = {
            "total_users": data.get("total_users"),
            "persona_breakdown": data.get("persona_breakdown", []),
            "converter_pct": data.get("converter_pct"),
            "biggest_leak_segment": data.get("biggest_leak_segment"),
            "conversion_signal_event_count": data.get("conversion_signal_event_count"),
            "narrative": data.get("narrative", {}),
        }
    else:
        # Generic fallback — expose top-level scalar values
        facts["key_metrics"] = {
            k: v for k, v in data.items()
            if isinstance(v, (int, float, str, bool)) and v is not None
        }

    return facts


def tool_aggregate_results(session_id: str) -> dict:
    """
    Collect all completed analysis results for a session.
    Reads from SessionState.results.
    Groups by analysis_type for easy cross-referencing.

    Args:
        session_id: current session

    Returns:
        dict with:
            status: success | no_results
            results_by_type: dict keyed by analysis_type
            results_by_id: dict keyed by analysis_id
            available_types: list of analysis types done
            total_results: int
            dataset_type: str (from session state)
            column_roles: dict (from session state)
            fact_sheet: dict — pre-parsed key metrics per node for grounding.
                         Synthesis agent MUST cite only values from fact_sheet.
    """
    try:
        from main import sessions
        state = sessions.get(session_id)

        results_from_state: dict = {}
        if state and state.results:
            results_from_state = dict(state.results)

        if not results_from_state:
            try:
                from tools.code_executor import _result_store
                prefix = f"{session_id}:"
                for key, val in _result_store.items():
                    if isinstance(val, dict) and val.get("status") == "success":
                        if key.startswith(prefix):
                            analysis_id = key[len(prefix):]
                        else:
                            analysis_id = key
                        results_from_state[analysis_id] = val
            except Exception:
                pass

        if not results_from_state:
            return {
                "status":          "no_results",
                "results_by_type": {},
                "results_by_id":   {},
                "available_types": [],
                "total_results":   0,
                "dataset_type":    "unknown",
                "column_roles":    {},
                "fact_sheet":      {},
            }

        results_by_type = {}
        results_by_id   = {}
        fact_sheet      = {}

        # Read DAG node map from session for node_id lookups
        dag = {}
        if state:
            plan = getattr(state, "analysis_plan", {}) or {}
            for node in plan.get("dag", []):
                nid = node.get("id")
                atype = node.get("analysis_type")
                if nid and atype:
                    dag[atype] = nid

        for analysis_id, result in results_from_state.items():
            atype = result.get("analysis_type", "unknown")
            results_by_type[atype] = result
            results_by_id[analysis_id] = result

            # Determine node_id from DAG or fall back to analysis_id
            node_id = dag.get(atype, analysis_id)
            fact_sheet[node_id] = _extract_node_facts(node_id, analysis_id, result)

        dataset_type = getattr(state, "dataset_type", "") if state else ""
        semantic_map = getattr(state, "semantic_map", {}) if state else {}
        column_roles = semantic_map.get(
            "column_roles", {}
        ) if isinstance(semantic_map, dict) else {}

        import math
        def _clean(obj):
            if isinstance(obj, dict):
                return {k: _clean(v) for k, v in obj.items()}
            elif isinstance(obj, list):
                return [_clean(x) for x in obj]
            
            if hasattr(obj, "item"):
                try:
                    obj = obj.item()
                except Exception:
                    pass
            
            if obj is None:
                return None
            elif isinstance(obj, float) and (math.isnan(obj) or math.isinf(obj)):
                return None
            elif isinstance(obj, (bool, int, float, str)):
                return obj
            else:
                s = str(obj)
                if s in ("<NA>", "nan", "NaN"):
                    return None
                return s

        return _clean({
            "status":          "success",
            "results_by_type": results_by_type,
            "results_by_id":   results_by_id,
            "available_types": list(results_by_type.keys()),
            "total_results":   len(results_by_id),
            "dataset_type":    dataset_type,
            "column_roles":    column_roles,
            "fact_sheet":      fact_sheet,
        })

    except Exception as e:
        import traceback
        print(f"Aggregation error: {traceback.format_exc()}")
        return {
            "status":          "no_results",
            "results_by_type": {},
            "results_by_id":   {},
            "available_types": [],
            "total_results":   0,
            "dataset_type":    "unknown",
            "column_roles":    {},
            "fact_sheet":      {},
            "error":           str(e),
        }




def _validate_synthesis_grounding(synthesis: dict, fact_sheet: dict, session_id: str = "") -> dict:
    """
    Lightweight grounding validator — checks that the synthesis cites node IDs
    and contains all required structural keys.
    Returns a metadata dict with: is_valid, warnings, citation_count.
    """
    import re
    warnings_found = []
    citation_count = 0

    # Check required top-level keys — only mandate the three universal sections;
    # personas/intervention_strategies may be absent for non-behavioural datasets.
    required_keys = ["executive_summary", "detailed_insights", "conversational_report"]
    for key in required_keys:
        if key not in synthesis:
            warnings_found.append(f"MISSING KEY: '{key}' not found in synthesis output.")

    # Check executive_summary has content
    ex = synthesis.get("executive_summary", {})
    if not ex.get("overall_health"):
        warnings_found.append("WEAK: executive_summary.overall_health is empty.")
    if not ex.get("top_priorities"):
        warnings_found.append("WEAK: executive_summary.top_priorities is empty.")

    # Check for node citation pattern — matches [A1], [C1], [A1: type], [C2: custom] etc.
    synthesis_str = json.dumps(synthesis)
    citations = re.findall(r'\[[AC]\d+[^\]]*\]', synthesis_str)
    citation_count = len(citations)
    if citation_count < 3:
        warnings_found.append(
            f"LOW CITATION: Only {citation_count} node ID citations found. "
            "Synthesis should cite [AX]/[CX] or [AX: type] for every quantitative claim."
        )
        try:
            from tools.monitor import emit
            emit(session_id, "synthesis_low_citation", {"citation_count": citation_count}, severity="warning")
        except Exception as _emit_err:
            logging.warning(f"Failed to emit low citation warning: {_emit_err}")

    # Check insights have individual top_finding
    # detailed_insights can be {"insights": [...]} or a bare list — handle both
    _di = synthesis.get("detailed_insights", {})
    insights = _di if isinstance(_di, list) else _di.get("insights", [])
    for i, ins in enumerate(insights):
        if not ins.get("ai_summary"):
            warnings_found.append(f"INSIGHT[{i}]: ai_summary is empty.")
        if not ins.get("how_to_fix"):
            warnings_found.append(f"INSIGHT[{i}]: how_to_fix steps are empty.")

    # Check entity segments / key_segments if a segment section was included
    _p = synthesis.get("key_segments", synthesis.get("personas", {}))
    personas = _p.get("segments", _p.get("personas", [])) if isinstance(_p, dict) else _p
    if (synthesis.get("key_segments") is not None or synthesis.get("personas") is not None) and not personas:
        warnings_found.append("WEAK: key_segments section present but no segments defined.")

    # Check conversational_report has content
    conv = synthesis.get("conversational_report", "")
    if len(str(conv)) < 800:
        warnings_found.append("WEAK: conversational_report is too short (< 800 chars) — narrative lacks depth.")

    is_valid = len([w for w in warnings_found if w.startswith("MISSING")]) == 0

    return {
        "is_valid": is_valid,
        "citation_count": citation_count,
        "warnings": warnings_found,
        "fact_sheet_nodes_available": list(fact_sheet.keys()),
    }


def tool_submit_synthesis(
    session_id: Annotated[str, Field(description="Active pipeline session ID")],
    synthesis_json_str: Annotated[str, Field(description="Complete synthesis result as a JSON string matching the required output schema")],
    reasoning_notes: Annotated[str, Field(description="2-3 sentence summary of key deductions made during synthesis. Stored and injected on retry.", default="")] = "",
    output_folder: Annotated[str, Field(description="Absolute path to the session output directory. Copy exactly from the prompt.", default="")] = "",
) -> str:
    """
    Submit the complete synthesis result.
    MUST be called as the last step.
    output_folder: absolute path to the session output directory (passed in the prompt in A2A mode).
    reasoning_notes: brief summary of your key deductions (2-3 sentences).
    These are stored and injected back on retry so you build on prior thinking.
    Runs DataLog grounding validation before storing.
    """
    try:
        if synthesis_json_str.strip().startswith("```"):
            lines = synthesis_json_str.strip().split("\n")
            if lines[0].startswith("```"): lines = lines[1:]
            if lines and lines[-1].startswith("```"): lines = lines[:-1]
            synthesis_json_str = "\n".join(lines).strip()
            
        import re
        match = re.search(r'```(?:json)?\s*(.*?)\s*```', synthesis_json_str, re.DOTALL)
        if match:
            synthesis_json_str = match.group(1)
        else:
            first_brace = synthesis_json_str.find('{')
            last_brace = synthesis_json_str.rfind('}')
            if first_brace != -1 and last_brace != -1:
                synthesis_json_str = synthesis_json_str[first_brace:last_brace+1]

        def _repair_json(s):
            # 1. Smart quotes -> straight quotes
            s = s.replace('\u201c', '"').replace('\u201d', '"')
            s = s.replace('\u2018', "'").replace('\u2019', "'")
            # 2. Trailing commas before } or ]
            s = re.sub(r',\s*([}\]])', r'\1', s)
            # 3. Extract first complete JSON object (handles "extra data" / double objects)
            first_open = s.find('{')
            if first_open != -1:
                depth = 0
                for i in range(first_open, len(s)):
                    if s[i] == '{': depth += 1
                    elif s[i] == '}':
                        depth -= 1
                        if depth == 0:
                            s = s[:i+1]
                            break
            # 4. Balance unclosed brackets
            open_b = s.count('{'); close_b = s.count('}')
            if open_b > close_b: s += '}' * (open_b - close_b)
            open_sq = s.count('['); close_sq = s.count(']')
            if open_sq > close_sq: s += ']' * (open_sq - close_sq)
            # 5. Fix invalid \escape sequences (e.g. \_word from column names)
            valid_esc = set('"\\bfnrtu/')
            out = []
            i = 0
            while i < len(s):
                if s[i] == '\\' and i + 1 < len(s) and s[i+1] not in valid_esc:
                    out.append('\\\\')
                else:
                    out.append(s[i])
                i += 1
            s = ''.join(out)
            # 6. Escape unescaped control characters inside JSON strings
            result = []
            in_str = False
            i = 0
            while i < len(s):
                c = s[i]
                if c == '"' and (i == 0 or s[i-1] != '\\'):
                    in_str = not in_str
                    result.append(c)
                elif in_str and c == '\n':
                    result.append('\\n')
                elif in_str and c == '\r':
                    result.append('\\r')
                elif in_str and c == '\t':
                    result.append('\\t')
                else:
                    result.append(c)
                i += 1
            return ''.join(result)

        try:
            synthesis = json.loads(synthesis_json_str)
        except json.JSONDecodeError as _jde:
            _repaired = _repair_json(synthesis_json_str)
            try:
                synthesis = json.loads(_repaired)
                print(f"[Synthesis] JSON repaired (original error: {_jde.msg} at char {_jde.pos})")
            except json.JSONDecodeError as _jde2:
                raise json.JSONDecodeError(
                    f"JSON parse failed after repair. Original: {_jde.msg}. After repair: {_jde2.msg}",
                    _jde2.doc, _jde2.pos
                ) from _jde2

        # --- MINIMUM QUALITY GUARD ---
        # Reject synthesis that is too shallow and force a retry.
        # This prevents the pipeline accepting one-liner summaries as complete output.
        _quality_failures = []

        _exec = synthesis.get("executive_summary", {})
        _overall_health = str(_exec.get("overall_health", ""))
        if len(_overall_health) < 150:
            _quality_failures.append(
                f"executive_summary.overall_health is too short ({len(_overall_health)} chars, minimum 150). "
                "Re-write with 3+ specific stats citing node IDs."
            )

        _insights = synthesis.get("detailed_insights", {})
        if isinstance(_insights, dict):
            _insights = _insights.get("insights", [])
        if len(_insights) == 0:
            _quality_failures.append("detailed_insights.insights is empty — must have one card per analysis node.")
        else:
            for _i, _ins in enumerate(_insights):
                _summary = str(_ins.get("ai_summary", ""))
                if len(_summary) < 80:
                    _quality_failures.append(
                        f"detailed_insights.insights[{_i}].ai_summary is too short ({len(_summary)} chars, minimum 80). "
                        "Must include: (a) the key metric with [NodeID], (b) what it means, (c) an internal comparison to another node finding. Do NOT invent benchmarks."
                    )
                _rc = str(_ins.get("root_cause_hypothesis", ""))
                if len(_rc) < 60:
                    _quality_failures.append(
                        f"detailed_insights.insights[{_i}].root_cause_hypothesis is too short ({len(_rc)} chars, minimum 60). "
                        "Must cite at least two node IDs in a causal chain."
                    )

        _conv = str(synthesis.get("conversational_report", ""))
        if len(_conv) < 1500:
            _quality_failures.append(
                f"conversational_report is too short ({len(_conv)} chars, minimum 1500). "
                "Must be a full narrative section covering all major findings with cited metrics."
            )

        # Fix 3: Enforce required section headers in conversational_report
        _required_headers = ["# Key Findings", "# Action Roadmap", "# Confidence Assessment"]
        _missing_headers = [h for h in _required_headers if h not in _conv]
        if _missing_headers:
            _quality_failures.append(
                f"conversational_report is missing required section headers: {_missing_headers}. "
                "The report MUST contain exactly these markdown headers: "
                "'# Key Findings', '# Action Roadmap', '# Confidence Assessment'."
            )

        # Fix 2: Enforce cross_metric_connections — scaled by available results
        # With 1 node: 0 connections needed; 2 nodes: 1; 3+: 2
        _cmc_raw = synthesis.get("cross_metric_connections", {})
        if isinstance(_cmc_raw, list):
            _connections = _cmc_raw
        elif isinstance(_cmc_raw, dict):
            _connections = _cmc_raw.get("connections", [])
        else:
            _connections = []
        _n_insights = len(_insights) if '_insights' in dir() else 2
        _min_connections = max(0, min(2, _n_insights - 1))
        if len(_connections) < _min_connections:
            _quality_failures.append(
                f"cross_metric_connections.connections has {len(_connections)} entr"
                f"{'y' if len(_connections) == 1 else 'ies'} (minimum {_min_connections} required). "
                "Each connection MUST cite two different [AX] node IDs and explain the causal mechanism."
            )
        else:
            import re as _re_cmc
            for _ci, _conn in enumerate(_connections):
                if not isinstance(_conn, dict):
                    continue
                _fa = str(_conn.get("finding_a", ""))
                _fb = str(_conn.get("finding_b", ""))
                _cited = set(_re_cmc.findall(r'\[[AC]\d+\]', _fa + _fb))
                if len(_cited) < 2:
                    _quality_failures.append(
                        f"cross_metric_connections.connections[{_ci}] cites fewer than 2 distinct node IDs "
                        f"(found: {sorted(_cited) if _cited else 'none'}). "
                        "finding_a and finding_b must each reference a different [AX]/[CX] node."
                    )

        if _quality_failures:
            # Store the LLM's reasoning from this attempt so the retry can
            # build on it rather than starting from scratch.
            if reasoning_notes and reasoning_notes.strip():
                _reasoning_store[session_id] = reasoning_notes.strip()
                print(f"[Synthesis QA] Stored reasoning notes for {session_id} ({len(reasoning_notes)} chars)")

            # Include prior reasoning in the rejection message so the LLM
            # knows exactly what it already worked out and only fixes gaps.
            _prior_reasoning = _reasoning_store.get(session_id, "")
            _reasoning_context = ""
            if _prior_reasoning:
                _reasoning_context = (
                    f"\nYour reasoning from this attempt:\n"
                    f"{_prior_reasoning}\n"
                    f"Build on this — do NOT start from scratch. Only fix the issues below.\n"
                )

            _msg = (
                "SYNTHESIS REJECTED — quality below minimum standards."
                + _reasoning_context +
                "\nFix specifically:\n"
                + "\n".join(f"  • {f}" for f in _quality_failures)
            )
            print(f"[Synthesis QA] REJECTED for {session_id}: {len(_quality_failures)} issue(s)")
            return _msg

        print(f"[Synthesis QA] Passed for {session_id} — {len(_insights)} insights, "
              f"conv_report={len(_conv)} chars")

        # Run DataLog grounding validation
        try:
            from main import sessions
            state = sessions.get(session_id)
            current_fact_sheet = {}
            if state and hasattr(state, "results"):
                # Build a minimal fact_sheet for validation context
                # Guard against non-dict results (e.g. lists) which cause AttributeError on .get()
                for aid, result in state.results.items():
                    if not isinstance(result, dict):
                        continue
                    atype = result.get("analysis_type", "unknown")
                    current_fact_sheet[aid] = {"analysis_type": atype, "status": result.get("status", "")}
        except Exception:
            current_fact_sheet = {}

        validation = _validate_synthesis_grounding(synthesis, current_fact_sheet, session_id=session_id)
        synthesis["_datalog_validation"] = validation

        # Synthesis passed — clear reasoning store (no longer needed)
        _reasoning_store.pop(session_id, None)

        # Mark synthesis as quality-confirmed — read by LoopAgent terminator (#7)
        synthesis["_qc_passed"] = True

        # Store synthesis FIRST — before any print statements that could crash on Windows cp1252
        with _synthesis_lock:
            _synthesis_store[session_id] = synthesis

        try:
            from main import sessions
            state = sessions.get(session_id)
        except Exception:
            state = None
        if state:
            state.synthesis = synthesis

        # Write file cache — works in BOTH single-server and A2A multi-server mode.
        # In A2A mode state is None, so we fall back to the _a2a_sessions.json registry
        # that orchestrator writes before calling any A2A agent.
        try:
            import os as _os
            _abs_out = None
            # Source A: output_folder parameter (A2A mode — LLM extracts from prompt)
            if output_folder and output_folder.strip():
                _abs_out = output_folder.strip()
            # Source B: state.output_folder (single-server mode)
            if not _abs_out and state:
                _out = getattr(state, "output_folder", None)
                if _out:
                    _adk_root = _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
                    _abs_out = _os.path.join(_adk_root, "output", _out) if not _os.path.isabs(_out) else _out
            # Source C: A2A session registry fallback
            if not _abs_out:
                try:
                    from agent_servers.a2a_orchestrator import lookup_session
                    _abs_out = lookup_session(session_id) or None
                except Exception:
                    pass
            if _abs_out:
                _os.makedirs(_abs_out, exist_ok=True)
                _tmp = _os.path.join(_abs_out, "_synthesis_cache.json")
                with open(_tmp, "w", encoding="utf-8") as _f:
                    json.dump(synthesis, _f)
                print(f"INFO: synthesis cache written to {_tmp}")
            else:
                print(f"WARNING: synthesis cache not written — output_folder unknown for {session_id}")
        except Exception as _ce:
            print(f"WARNING: synthesis cache write failed: {_ce}")
            if state:
                try:
                    _int = synthesis.get("recommendations", synthesis.get("intervention_strategies", {}))
                    _per = synthesis.get("key_segments", synthesis.get("personas", {}))
                    _cmc = synthesis.get("cross_metric_connections", {})
                    msg = create_message(
                        sender="synthesis_agent",
                        recipient="orchestrator",
                        intent=Intent.SYNTHESIS_COMPLETE,
                        payload={
                            "critical_count": _int.get("critical_count", 0) if isinstance(_int, dict) else 0,
                            "segment_count": _per.get("segment_count", _per.get("persona_count", 0)) if isinstance(_per, dict) else len(synthesis.get("key_segments", synthesis.get("personas", []))),
                            "connection_count": _cmc.get("connection_count", 0) if isinstance(_cmc, dict) else len(synthesis.get("cross_metric_connections", [])),
                        },
                        session_id=session_id,
                    )
                    state.post_message(msg)
                except Exception:
                    pass

        # Safe logging after synthesis is already stored
        try:
            if validation["warnings"]:
                print(f"[Synthesis Validator] {len(validation['warnings'])} warning(s):")
                for w in validation["warnings"]:
                    print(f"  [WARN] {w}")
            print(f"[Synthesis Validator] Citations found: {validation['citation_count']} | Valid: {validation['is_valid']}")
        except Exception:
            pass  # Terminal encoding issues must never block synthesis storage

        return f"Synthesis stored for session {session_id}. Ready for DAG Builder."
    except Exception as e:
        import traceback
        traceback.print_exc()
        return f"Error storing synthesis: {str(e)}"


_synthesis_agent_instance = None

def get_synthesis_agent():
    global _synthesis_agent_instance
    if _synthesis_agent_instance is None:
        from google.adk.agents import Agent
        from tools.model_config import get_model
        _synthesis_agent_instance = Agent(
            name="synthesis_agent",
            model=get_model("synthesis"),
            description="Interpretation layer. Receives all analysis results and generates deep narrative, personas, strategies, and executive summary.",
            instruction=(
                "You are a Senior Data Intelligence Analyst operating as the final interpretation layer of a multi-agent analytics pipeline. "
                "You receive structured, pre-computed analysis results from up to 20 analysis nodes and transform them into a single, definitive intelligence report. "
                "Your output will be read by decision-makers and business stakeholders — it must be SPECIFIC, EVIDENCE-BACKED, and ACTIONABLE.\n\n"

                "## CORE MANDATE: THE DATALOG STANDARD\n"
                "Every claim you make MUST be traceable to data. You are NOT a language model generating generic business advice. "
                "You are a data analyst whose ONLY source of truth is the tool results returned to you. "
                "If a number does not appear in a tool result, you CANNOT state that number. If a trend is not in the data, you CANNOT claim it.\n\n"

                "## WORKFLOW\n"
                "1. Call `tool_aggregate_results(session_id)` to receive ALL completed analysis results, grouped by node ID and analysis type.\n"
                "2. Study the results. For EACH node, check the `decision_maker_takeaway` field in the fact_sheet first — "
                "this is a pre-generated insight summarising what matters most. Use it as your starting point, then deepen it with the raw numbers.\n"
                "3. Identify cross-analysis patterns using the DAG DEPENDENCY GRAPH provided in the prompt:\n"
                "   - DEPENDENT nodes (has depends_on): a child node result is caused or constrained by its parent — reason causally, not just correlationally.\n"
                "   - AMPLIFYING pairs: two independent nodes that converge on the same entity stage — both findings reinforce the same conclusion.\n"
                "   - CONTRADICTING signals: one node shows critical severity but a related node shows low impact — explain the discrepancy, do not ignore it.\n"
                "4. Build your synthesis JSON and call `tool_submit_synthesis(session_id=<session_id>, synthesis_json_str=<json>, "
                "output_folder=<output_folder from prompt>, reasoning_notes=<2-3 sentence summary>)`. "
                "The output_folder and session_id are provided at the top of your prompt — copy them exactly. "
                "reasoning_notes is a 2-3 sentence plain-English summary of your key deductions (e.g. 'Node A1 showed 70% bounce rate which I connected to A5 dropout peak...'). "
                "This is stored and fed back to you if the submission is rejected, so you can build on it rather than starting over.\n\n"

                "## EVIDENCE CITATION RULES (Non-Negotiable)\n"
                "- Node IDs use the format `[A1]`, `[A2]`, etc. for discovered analyses, and `[C1]`, `[C2]`, etc. for user-requested custom analyses. Cite both equally.\n"
                "- EVERY quantitative claim (a percentage, a count, a ratio) MUST be followed by the analysis node it came from: `[A1: session_detection]` or `[C1: custom_type]`.\n"
                "- EVERY root cause hypothesis MUST reference at least TWO data signals to support it (e.g., `[A2] + [C1]`).\n"
                "- If an analysis node has `status: error` or `status: insufficient_data`, you MUST write 'Insufficient data from [NodeID]' for that insight — do NOT invent a finding.\n"
                "- `top_priorities` in the executive summary MUST cite the specific node and metric that makes it a priority.\n"
                "- Custom analyses (CX nodes) are user-requested and high-priority — ALWAYS include their findings prominently.\n\n"

                "## ANTI-HALLUCINATION RULES\n"
                "These are the boundaries of what you are allowed to state:\n"
                "- ALLOWED: Stating a number that appears verbatim in a tool result.\n"
                "- ALLOWED: Inferring a trend direction (e.g., 'retention declines') if the tool result shows consecutive decreasing values.\n"
                "- ALLOWED: Estimating business impact IF you show your calculation (e.g., 'Estimated impact = affected_entities × average_outcome_value').\n"
                "- FORBIDDEN: Stating a specific percentage that is not in any tool result.\n"
                "- FORBIDDEN: Claiming a correlation between two metrics unless the `correlation_matrix` analysis [AX] was run and shows r > 0.5.\n"
                "- FORBIDDEN: Naming a specific entity as a persona archetype unless `user_segmentation` was run and returned cluster labels.\n\n"

                "## DOMAIN-AGNOSTIC REASONING\n"
                "You do NOT know the industry. You do NOT know what the product, service, or system is. You reason ONLY from DATA SHAPES:\n"
                "- A high `avg_repetitions` in friction_detection means entities are looping — do NOT assume this is a 'payment gateway' issue unless the event values explicitly mention payment.\n"
                "- Persona names MUST come from data patterns, not from industry archetypes. 'Struggling Explorer' is acceptable only if the data shows high event count + low outcome. 'Shopper' is NOT acceptable unless that exact label appears in a tool result.\n"
                "- Interventions MUST be described in terms of data signals (events, thresholds, timeframes) — never assume a UI, CRM, or notification system exists.\n"
                "- The word 'user' is fine if `entity_col` represents people. If the entities are products, transactions, samples, or records, use the appropriate term.\n"
                "- Financial estimates are ALWAYS labeled as 'estimated' and show the formula used.\n"
                "- If the dataset is clearly non-behavioral (e.g., sales records, sensor readings, survey responses), SKIP the `personas` and `intervention_strategies` sections and focus on `detailed_insights` + `conversational_report`.\n\n"

                "## REQUIRED OUTPUT STRUCTURE (All keys mandatory)\n\n"

                "### executive_summary\n"
                "{\n"
                "  'overall_health': 'One paragraph. Must cite 3+ specific stats with node IDs. Pattern: [AX] shows Y% of Z.',\n"
                "  'top_priorities': ['Priority 1: __METRIC__ at __VALUE__ [NodeID]', 'Priority 2: ...'],\n"
                "  'business_impact': 'Quantified consequence. Show formula if estimating. Label as estimated if not directly in data.',\n"
                "  'resource_allocation': 'Specific recommendation on where to focus, referencing the highest-severity node.',\n"
                "  'timeline': 'Quick Wins (1-2 weeks): [...]. Medium Fixes (1 month): [...]. Strategic (3 months): [...]'\n"
                "}\n\n"

                "### detailed_insights — ONE card per completed analysis node\n"
                "⚠️  CRITICAL: Every text field below MUST contain real written content. "
                "Empty strings (\"\") are NEVER allowed. Write the content inline — do not submit a skeleton.\n\n"
                "EXAMPLE of a correctly filled card (copy this quality for every node):\n"
                "{\n"
                "  'insights': [\n"
                "    {\n"
                "      'title': '70.5% Bounce Rate — Majority of Sessions Are Single-Event',\n"
                "      'ai_summary': '[A1] detected that 70.5% of all 39,066 sessions consist of exactly one event, meaning users abandon after a single interaction with no further engagement. This is the highest-severity finding in the dataset — it dwarfs the dropout rate from [A5] (42%) which only measures multi-step sessions, confirming the bounce problem is upstream of the funnel entirely.',\n"
                "      'root_cause_hypothesis': '[A1] shows 70.5% single-event sessions → [A5] shows dropout spikes at Push_Failure event → users encountering Push_Failure on first interaction have no recovery path → this technical failure is the primary driver of the bounce rate, not user intent.',\n"
                "      'possible_causes': [\n"
                "        'Push_Failure event triggers on first load for 70%+ of users, per [A5] dropout data',\n"
                "        'Session detection [A1] confirms no second event follows Push_Failure in 68% of affected sessions',\n"
                "        'Event taxonomy [A2] classifies Push_Failure as a system event — not user-initiated — confirming it is a backend issue'\n"
                "      ],\n"
                "      'downstream_implications': 'Every downstream funnel metric is understated — conversion rates, journey lengths, and retention figures are computed only on the 29.5% of users who survive past the bounce. Fixing Push_Failure would roughly 3x the addressable funnel population.',\n"
                "      'fix_priority': 'critical',\n"
                "      'how_to_fix': [\n"
                "        'Step 1: Instrument Push_Failure event from [A5] with device/OS breakdown to identify affected cohort',\n"
                "        'Step 2: Deploy a silent retry on Push_Failure before surfacing error to user — [A1] data suggests most sessions would continue if the first event succeeded'\n"
                "      ]\n"
                "    }\n"
                "  ]\n"
                "}\n\n"
                "Now write ONE card exactly like this for EACH analysis node in the fact_sheet. "
                "Replace all values with findings from your actual data — never copy the example numbers.\n\n"


                "### key_segments — infer 2-4 entity archetypes from segmentation / behavioral data\n"
                "ONLY include this section if the analysis results support it "
                "(i.e., at least one of `session_classification`, `user_segmentation`, `funnel_analysis`, or `dropout_analysis` ran successfully).\n"
                "If none of those analyses were run, OMIT the `key_segments` key entirely rather than fabricating archetypes.\n\n"
                "NAMING: Name archetypes from what the DATA shows — derive the name from the entity's OBSERVED PATTERN, not from any assumed industry. "
                "Examples of data-driven names: 'Deep Explorer' (many events, no outcome), 'Fast Converter' (few steps, high completion rate), "
                "'Abandoner at Step 3' (consistent exit point). NEVER name archetypes after marketing demographics or industry personas "
                "unless those exact labels appear verbatim in a tool result.\n\n"
                "If `session_classification` ran [AX], use the EXACT segment labels it returned (they are data-derived from THIS dataset). "
                "If `user_segmentation` ran instead, use its cluster descriptions. "
                "Never import segment names from prior domain knowledge.\n"
                "{\n"
                "  'segment_count': 3,\n"
                "  'segments': [\n"
                "    {\n"
                "      'name': 'Derive from data patterns, e.g. High-Engagement Non-Converter or Early Dropout',\n"
                "      'size': 'N entities (X%) [NodeID that provided this breakdown]',\n"
                "      'profile': 'Data-derived description citing the specific events/metrics that define this group. [AX]',\n"
                "      'pain_points': ['Pain point grounded in a specific event or metric from a tool result'],\n"
                "      'opportunities': ['Concrete action tied to a specific finding from [AX]'],\n"
                "      'priority_level': 'high|medium|low'\n"
                "    }\n"
                "  ]\n"
                "}\n\n"

                "### recommendations — Concrete, evidence-backed actions\n"
                "ONLY include this section if at least one analysis returned severity `critical` or `high`, "
                "or if `intervention_triggers` was run. Omit the key entirely for descriptive/statistical datasets "
                "where no actionable recommendation signal was found.\n\n"
                "Recommendations MUST be domain-agnostic. Describe WHAT to do in terms of the data events/metrics found — "
                "do NOT assume a UI, an email system, or a SaaS product. Instead, describe the action in terms of "
                "the triggering condition and the outcome variable from the data.\n"
                "{\n"
                "  'critical_count': 1,\n"
                "  'strategies': [\n"
                "    {\n"
                "      'severity': 'critical|high|medium|low',\n"
                "      'title': 'Title referencing the specific event, metric, or stage from [AX]',\n"
                "      'realtime_interventions': [\n"
                "        'Trigger an action WHEN [specific event from AX] occurs for the Nth time — cite the exact threshold from the data [AX]'\n"
                "      ],\n"
                "      'proactive_outreach': [\n"
                "        'Target entities who completed [event X] but NOT [event Z] within [timeframe derived from data] [AX]'\n"
                "      ]\n"
                "    }\n"
                "  ]\n"
                "}\n\n"

                "### cross_metric_connections — Cross-node synthesis\n"
                "ONLY include connections where you can cite TWO different node IDs.\n"
                "{\n"
                "  'connection_count': 2,\n"
                "  'connections': [\n"
                "    {\n"
                "      'finding_a': '[A1] 38% of sequences end after 1 step',\n"
                "      'finding_b': '[A3] Highest friction at the first recorded event',\n"
                "      'synthesized_meaning': 'Short sequences are correlated with high friction at the first recorded step.'\n"
                "    }\n"
                "  ]\n"
                "}\n\n"

                "### conversational_report — Long-form markdown narrative\n"
                "Write a detailed markdown document formatted as a professional data intelligence report. "
                "Adapt the section structure to the DATASET TYPE and analyses that were actually run — "
                "do not force product/UX framing onto non-behavioral datasets.\n\n"
                "REQUIRED structure (use these section titles exactly, adapt only sub-headings to the data):\n"
                "# Key Findings\n"
                "## What the Data Shows (2-3 paragraphs summarising the most important patterns, citing [NodeIDs])\n"
                "## Finding Inventory (markdown table: Finding | Evidence [NodeID] | Severity | Estimated Impact)\n"
                "# Entity Profiles  (ONLY if segmentation data is available — omit this section entirely otherwise)\n"
                "## Archetype Profiles (one subsection per segment, named from data)\n"
                "# Action Roadmap\n"
                "## Immediate Actions (achievable quickly, citing the specific metric/event to target)\n"
                "## Strategic Initiatives (longer-horizon, with data justification)\n"
                "# Confidence Assessment\n"
                "| Claim | Evidence [NodeID] | Confidence Level |\n"
                "|---|---|---|\n"
                "| Each major claim | Which node supports it | High/Medium/Low based on data completeness |\n\n"

                "## DO's\n"
                "- DO call `tool_aggregate_results` first before writing anything.\n"
                "- DO cite node IDs in EVERY quantitative claim.\n"
                "- DO label estimates clearly with 'estimated' and show the formula.\n"
                "- DO include an insight card for EVERY analysis node that returned `status: success`, including custom (CX) nodes.\n"
                "- DO use `tool_submit_synthesis(session_id, synthesis_json_str, reasoning_notes)` as your LAST action — pass your key reasoning as the third argument.\n\n"

                "## DON'Ts\n"
                "- DON'T fabricate numbers. If a metric isn't in the tool result, it doesn't exist.\n"
                "- DON'T write generic recommendations like 'Improve UX' or 'Add A/B tests' without specific node evidence.\n"
                "- DON'T name a correlation without the `correlation_matrix` result supporting it.\n"
                "- DON'T write placeholder text like 'N/A', 'See data', or 'Data not available' — write instead what IS known.\n"
                "- DON'T output raw JSON with unescaped newlines — the JSON must be parseable by Python's `json.loads()`.\n"
                "- DON'T invent industry benchmarks. You have no external knowledge of what is 'normal' — only compare within the data.\n\n"

                "## MANDATORY SELF-REVIEW BEFORE CALLING tool_submit_synthesis\n"
                "Before submitting, verify each point — a rejected synthesis wastes a full LLM retry:\n"
                "- [ ] Every quantitative claim in detailed_insights cites a [NodeID] with the exact number from the fact sheet.\n"
                "- [ ] Every root_cause_hypothesis is a causal chain citing at least 2 different [NodeIDs].\n"
                "- [ ] cross_metric_connections has at least 2 entries, each linking 2 DIFFERENT node IDs.\n"
                "- [ ] conversational_report contains all required headers: '# Key Findings', '# Action Roadmap', '# Confidence Assessment'.\n"
                "- [ ] Every critical/high insight has at least 2 specific how_to_fix steps naming the exact event/metric from [NodeID].\n"
                "- [ ] All estimated figures are labeled 'estimated' with the formula shown.\n"
            ),
            tools=[tool_aggregate_results, tool_submit_synthesis],
        )
    return _synthesis_agent_instance
